version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: emailcraft-postgres
    environment:
      POSTGRES_DB: emailcraft_ai
      POSTGRES_USER: emailcraft
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    networks:
      - emailcraft-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emailcraft -d emailcraft_ai"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and sessions (optional for later)
  redis:
    image: redis:7-alpine
    container_name: emailcraft-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - emailcraft-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin for database management (development only)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: emailcraft-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@emailcraft.ai
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - emailcraft-network
    profiles:
      - dev

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  emailcraft-network:
    driver: bridge